### ISSUE TITLE
automated maven warfile package fails, manual succeeds

### ISSUE THREAD

**Issue by donsizemore** [GlobalDataverseCommunityConsortium/dataverse-ansible#330]
currently using maven 3.8.8. special env vars (previously) necessary:

```
export JAVA_HOME=/usr/lib/jvm/jre-openjdk
export M2_HOME=/opt/maven
export MAVEN_HOME=/opt/maven
export PATH=${M2_HOME}/bin:${PATH}
```

**Comment by donsizemore** [comment]
errors are:

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.009 s <<< FAILURE! - in edu.harvard.iq.dataverse.settings.ConfigCheckServiceTest$TestDirNotExistent
edu.harvard.iq.dataverse.settings.ConfigCheckServiceTest$TestDirNotExistent.mkdirFails  Time elapsed: 0.007 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
        at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
        at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:31)
        at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:227)
        at edu.harvard.iq.dataverse.settings.ConfigCheckServiceTest$TestDirNotExistent.mkdirFails(ConfigCheckServiceTest.java:82)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in edu.harvard.iq.dataverse.settings.ConfigCheckServiceTest$TestDirNotWritable
[ERROR] edu.harvard.iq.dataverse.settings.ConfigCheckServiceTest$TestDirNotWritable.writeCheckFails  Time elapsed: 0.003 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
        at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
        at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:31)
        at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:227)
        at edu.harvard.iq.dataverse.settings.ConfigCheckServiceTest$TestDirNotWritable.writeCheckFails(ConfigCheckServiceTest.java:58)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```
