### ISSUE TITLE
TASK [dataverse : run sampledata] fails with "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 834: ordinal not in range(128)"

### ISSUE THREAD

**Issue by atc0005** [GlobalDataverseCommunityConsortium/dataverse-ansible#38]
```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "python3 create_sample_data.py", "delta": "0:11:37.408206", "end": "2020-08-28 22:20:09.554314", "msg": "non-zero return code", "rc": 1, "start": "2020-08-28 22:08:32.146108", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 77323    0     0  100 77323      0  76293  0:00:01  0:00:01 --:--:-- 76330\r100 77797  100   474  100 77323    267  43717  0:00:01  0:00:01 --:--:-- 43710\r100 77797  100   474  100 77323    267  43715  0:00:01  0:00:01 --:--:-- 43710\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n
   Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  926k  100   802  100  925k    968  1118k --:--:-- --:--:-- --:--:-- 1117k\r100  926k  100   802  100  925k    968  1117k --:--:-- --:--:-- --:--:-- 1117k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  926k  100   789  100  925k   1267  1486k --:--:-- --:--:-- --:--:-- 1485k\r100  926k  100   789  100  925k   1267  1486k --:--:-- --:--:-- --:--:-- 1485k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  926k  100   789  100  925k   2044  2397k --:--:-- --:--:-- --:--:-- 2397k\r100  926k  100   789  100  925k   2043  2397k --:--:-- --:--:-- --:--:-- 2391k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  926k  100   797  100  925k   1718  1996k --:--:-- --:--:-- --:--:-- 1994k\r100  926k  100   797  100  925k   1718  1995k --:--:-- --:--:-- --:--:-- 1994k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  926k  100   789  100  925k   1872  2196k --:--:-- --:--:-- --:--:-- 2198k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 84705  100   489  100 84216    912   153k --:--:-- --:--:-- --:--:--  153k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  926k  100   797  100  925k   1464  1700k --:--:-- --:--:-- --:--:-- 1701k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  201k  100   505  100  200k    571   227k --:--:-- --:--:-- --:--:--  227k\r100  201k  100   505  100  200k    571   227k --:--:-- --:--:-- --:--:--  227k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  926k  100   797  100  925k   1183  1374k --:--:-- --:--:-- --:--:-- 1373k\r100  926k  100   797  100  925k   1183  1373k --:--:-- --:--:-- --:--:-- 1373k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  926k  100   789  100  925k   1739  2040k --:--:-- --:--:-- --:--:-- 2043k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 3369k  100   480  100 3368k   1191  8359k --:--:-- --:--:-- --:--:-- 8380k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  227k  100   544  100  227k    883   369k --:--:-- --:--:-- --:--:--  368k\r100  227k  100   544  100  227k    883   369k --:--:-- --:--:-- --:--:--  368k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 3305k    0     0  100 3305k      0  3255k  0:00:01  0:00:01 --:--:-- 3256k\r100 3306k  100   496  100 3305k    317  2115k  0:00:01  0:00:01 --:--:-- 2116k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n
                      Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 5347k    0     0  100 5347k      0  5315k  0:00:01  0:00:01 --:--:-- 5320k\r100 5347k  100   496  100 5347k    325  3512k  0:00:01  0:00:01 --:--:-- 3510k\r100 5347k  100   496  100 5347k    325  3511k  0:00:01  0:00:01 --:--:-- 3510k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 14.3M    0     0  100 14.3M      0  14.1M  0:00:01  0:00:01 --:--:-- 14.1M\r100 14.3M    0     0  100 14.3M      0  7284k  0:00:02  0:00:02 --:--:-- 7284k\r100 14.3M    0     0  100 14.3M      0  4867k  0:00:03  0:00:03 --:--:-- 4868k\r100 14.3M    0     0  100 14.3M      0  3654k  0:00:04  0:00:04 --:--:-- 3655k\r100 14.3M  100   497  100 14.3M    123  3652k  0:00:04  0:00:04 --:--:-- 3652k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  332k  100   478  100  331k    996   691k --:--:-- --:--:-- --:--:--  692k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n
     Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 1757k  100   496  100 1757k    565  2003k --:--:-- --:--:-- --:--:-- 2003k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  656k  100   525  100  656k    567   708k --:--:-- --:--:-- --:--:--  708k\r100  656k  100   525  100  656k    567   708k --:--:-- --:--:-- --:--:--  708k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 10376  100   508  100  9868   1370  26615 --:--:-- --:--:-- --:--:-- 26670\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  865k  100   563  100  864k   1326  2036k --:--:-- --:--:-- --:--:-- 2039k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  103k  100   477  100  103k   1111   240k --:--:-- --:--:-- --:--:--  240k\r100  103k  100   477  100  103k   1111   240k --:--:-- --:--:-- --:--:--  240k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 1489k  100   496  100 1488k    630  1892k --:--:-- --:--:-- --:--:-- 1891k\r100 1489k  100   496  100 1488k    630  1892k --:--:-- --:--:-- --:--:-- 1891k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 10.1M    0     0  100 10.1M      0  10.0M  0:00:01  0:00:01 --:--:-- 10.0M\r100 10.1M    0     0  100 10.1M      0  5184k  0:00:02  0:00:02 --:--:-- 5185k\r100 10.1M  100   497  100 10.1M    182  3826k  0:00:02  0:00:02 --:--:-- 3825k\r100 10.1M  100   497  100 10.1M    182  3826k  0:00:02  0:00:02 --:--:-- 3825k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  515k  100   478  100  514k   1357  1462k --:--:-- --:--:-- --:--:-- 1466k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n
      Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  859k  100   489  100  858k   1347  2367k --:--:-- --:--:-- --:--:-- 2372k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  826k  100   475  100  826k   1469  2555k --:--:-- --:--:-- --:--:-- 2550k\r100  826k  100   475  100  826k   1468  2555k --:--:-- --:--:-- --:--:-- 2550k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 2891k  100   551  100 2891k    887  4654k --:--:-- --:--:-- --:--:-- 4648k\r100 2891k  100   551  100 2891k    886  4654k --:--:-- --:--:-- --:--:-- 4648k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 4065k  100   551  100 4064k    725  5351k --:--:-- --:--:-- --:--:-- 5348k\r100 4065k  100   551  100 4064k    725  5350k --:--:-- --:--:-- --:--:-- 5348k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 3103k  100   551  100 3103k    702  3956k --:--:-- --:--:-- --:--:-- 3953k\r100 3103k  100   551  100 3103k    702  3955k --:--:-- --:--:-- --:--:-- 3953k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 3046k  100   551  100 3046k    872  4822k --:--:-- --:--:-- --:--:-- 4820k\r100 3046k  100   551  100 3046k    872  4821k --:--:-- --:--:-- --:--:-- 4820k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 2892k  100   551  100 2891k    712  3737k --:--:-- --:--:-- --:--:-- 3740k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 3106k  100   551  100 3106k    716  4038k --:--:-- --:--:-- --:--:-- 4039k\r100 3106k  100   551  100 3106k    716  4038k --:--:-- --:--:-- --:--:-- 4033k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 2891k  100   551  100 2891k    878  4610k --:--:-- --:--:-- --:--:-- 4618k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 3048k  100   551  100 3047k    812  4491k --:--:-- --:--:-- --:--:-- 4494k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  989k  100   507  100  988k   1832  3572k --:--:-- --:--:-- --:--:-- 3582k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 3047k  100   551  100 3046k    809  4477k --:--:-- --:--:-- --:--:-- 4480k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  802k  100   498  100  801k   1562  2515k --:--:-- --:--:-- --:--:-- 2521k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 4033k  100   551  100 4032k    757  5547k --:--:-- --:--:-- --:--:-- 5554k\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 6009k  100   578  100 6008k   1271  12.9M --:--:-- --:--:-- --:--:-- 12.8M\r100 6009k  100   578  100 6008k   1271  12.9M --:--:-- --:--:-- --:--:-- 12.8M\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100 2993k  100   578  100 2992k   1594  8258k --:--:-- --:--:-- --:--:-- 8267k\nTraceback (most recent call last):\n  File \"create_sample_data.py\", line 56, in <module>\n    metadata = json.load(f)\n  File \"/usr/lib64/python3.6/json/__init__.py\", line 296, in load\n    return loads(fp.read(),\n  File \"/usr/lib64/python3.6/encodings/ascii.py\", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 834: ordinal not in range(128)", "stderr_l
```

Bits that stood out:

```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "python3 create_sample_data.py", "delta": "0:11:37.408206", "end": "2020-08-28 22:20:09.554314", "msg": "non-zero return code", "rc": 1,
```

```
Traceback (most recent call last):\n  File \"create_sample_data.py\", line 56, in <module>\n    metadata = json.load(f)\n  File \"/usr/lib64/python3.6/json/__init__.py\", line 296, in load\n    return loads(fp.read(),\n  File \"/usr/lib64/python3.6/encodings/ascii.py\", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 834: ordinal not in range(128)", 
```

Is this expected?

This is from the LXD environment that we're using and is the latest attempt to create an instance using sample data. I'll try to replicate using a traditional CentOS 7 VM (instead of a CentOS 7 LXD container).

**Comment by donsizemore** [comment]
That task is fed by https://github.com/IQSS/dataverse-sample-data and I seem to remember some trouble with it (I haven't used it in months). A good test would be to run it manually on the same container, if it's still up?

**Comment by atc0005** [comment]
> That task is fed by https://github.com/IQSS/dataverse-sample-data and I seem to remember some trouble with it (I haven't used it in months). A good test would be to run it manually on the same container, if it's still up?

Great suggestion. I was able to reproduce the error.

```ShellSession
Creating dataverse ubiquity-press.json in dataverse :root
{'name': 'Ubiquity Press Dataverse', 'alias': 'ubiquity-press', 'dataverseContacts': [{'contactEmail': 'ubiquity-press@mailinator.com'}], 'affiliation': '', 'description': 'Ubiquity Press is an open access publisher of peer-reviewed, academic journals. Our flexible publishing model makes journals affordable, and enables researchers around the world to find and access the information they need, without barriers. The following gives an overview of how we work. More information can be found in a recent interview with Chronicle of Higher Education: <a href="http://chronicle.com/blogs/profhacker/ubiquity/43312" rel="nofollow" target="_blank">"Open Access Ahoy: An Interview with Ubiquity Press"</a>.', 'dataverseType': 'JOURNALS'}
Dataverse ubiquity-press created.
<Response [201]>
Dataverse ubiquity-press published.
<Response [200]>
Creating dataverse jopd.json in dataverse ubiquity-press
{'name': 'Journal of Open Psychology Data (JOPD) Dataverse', 'alias': 'jopd', 'dataverseContacts': [{'contactEmail': 'jopd@mailinator.com'}], 'affiliation': 'Ubiquity Press', 'description': 'Datasets from data papers published in the Journal of Open Psychology Data (JOPD).', 'dataverseType': 'JOURNALS'}
Dataverse jopd created.
<Response [201]>
Dataverse jopd published.
<Response [200]>
Creating dataset flynn-effect-in-estonia.json in dataverse jopd
Traceback (most recent call last):
  File "create_sample_data.py", line 56, in <module>
    metadata = json.load(f)
  File "/usr/lib64/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 834: ordinal not in range(128)
```

Do you know whether I should file an issue in that repo or somewhere else?

**Comment by donsizemore** [comment]
yes, an issue in dataverse-sample-data would be best. thank you!

**Comment by atc0005** [comment]
> @donsizemore: yes, an issue in dataverse-sample-data would be best. thank you!

Done: IQSS/dataverse-sample-data#21
