### ISSUE TITLE
Installer failing

### ISSUE THREAD

**Issue by poikilotherm** [GlobalDataverseCommunityConsortium/dataverse-ansible#93]
For IQSS/dataverse#7422 we see the installer failing.

See https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/view/change-requests/job/PR-7422/5/consoleText

```
TASK [dataverse : patch installAppServer.py so that FILES_DIR points to the correct location] *** changed: [localhost]

TASK [dataverse : patch as-setup.sh so it doesn't hardcode siteUrl] ************ changed: [localhost]

TASK [dataverse : fire off installer] ****************************************** fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/bin/python /tmp/dvinstall/install.py -f --config_file=default.config --noninteractive > /tmp/dvinstall/install.out 2>&1", "delta": "0:01:28.098174", "end": "2020-11-21 03:49:37.978493", "msg": "non-zero return code", "rc": 1, "start": "2020-11-21 03:48:09.880319", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []} [WARNING]: Module remote_tmp /home/dataverse/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with the correct permissions manually 
```

Is this related to #6?

**Comment by donsizemore** [comment]
failing branch is `https://github.com/poikilotherm/dataverse/tree/7418-datasourcedefinition`

install.out error is `Failed to deploy the application!`

server.log says

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.gjc.util.MethodExecutor.runMethod(MethodExecutor.java:142)
        at com.sun.gjc.common.DataSourceObjectBuilder.constructDataSourceObject(DataSourceObjectBuilder.java:118)
        at com.sun.gjc.spi.ManagedConnectionFactoryImpl.getDataSource(ManagedConnectionFactoryImpl.java:1384)
        at com.sun.gjc.spi.XAManagedConnectionFactory.getDataSource(XAManagedConnectionFactory.java:167)
        at com.sun.gjc.spi.XAManagedConnectionFactory.createManagedConnection(XAManagedConnectionFactory.java:105)
        at com.sun.enterprise.resource.allocator.ConnectorAllocator.createResource(ConnectorAllocator.java:161)
        at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:920)
        at com.sun.enterprise.resource.pool.ConnectionPool.createResource(ConnectionPool.java:1209)
        at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:98)
        at com.sun.enterprise.resource.pool.ConnectionPool.addResource(ConnectionPool.java:287)
        at com.sun.enterprise.resource.pool.ConnectionPool.createResourceAndAddToPool(ConnectionPool.java:1532)
        at com.sun.enterprise.resource.pool.ConnectionPool.createResources(ConnectionPool.java:957)
        at com.sun.enterprise.resource.pool.ConnectionPool.initPool(ConnectionPool.java:235)
        at com.sun.enterprise.resource.pool.ConnectionPool.internalGetResource(ConnectionPool.java:528)
        at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:386)
        at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:244)
        at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:171)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:354)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)
        at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)
        at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:113)
        at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:138)
        at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:172)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:225)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:809)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:256)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:772)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:222)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:330)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:350)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:313)
        at org.glassfish.persistence.jpa.JPADeployer$2.visitPUD(JPADeployer.java:461)
        at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:525)
        at org.glassfish.persistence.jpa.JPADeployer.iterateInitializedPUsAtApplicationPrepare(JPADeployer.java:507)
        at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:408)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:562)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:561)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
snip

[2020-11-25T13:39:27.432+0000] [Payara 5.2020] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.resource.allocator] [tid: _ThreadID=83 _ThreadName=admin-thread-pool::admin-list
ener(1)] [timeMillis: 1606311567432] [levelValue: 900] [[
  RAR5038:Unexpected exception while creating resource for pool __SYSTEM/pools/__datasource_definition/dataverse/java:app/jdbc/dataverse. Exception : javax.resource.ResourceException: Access denied to e
xecute this method : setURL]]

[2020-11-25T13:39:27.433+0000] [Payara 5.2020] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors] [tid: _ThreadID=83 _ThreadName=admin-thread-pool::admin-listener(1)]
 [timeMillis: 1606311567433] [levelValue: 900] [[
  RAR5117 : Failed to obtain/create connection from connection pool [ __SYSTEM/pools/__datasource_definition/dataverse/java:app/jdbc/dataverse ]. Reason : com.sun.appserv.connectors.internal.api.Pooling
Exception: Access denied to execute this method : setURL]]

[2020-11-25T13:39:27.435+0000] [Payara 5.2020] [WARNING] [] [javax.enterprise.resource.resourceadapter.com.sun.gjc.spi] [tid: _ThreadID=83 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 
1606311567435] [levelValue: 900] [[
  RAR5114 : Error allocating connection : [Error in allocating a connection. Cause: Access denied to execute this method : setURL]]]

[2020-11-25T13:39:27.437+0000] [Payara 5.2020] [SEVERE] [] [org.eclipse.persistence.session./file:/usr/local/payara5/glassfish/domains/domain1/applications/dataverse/WEB-INF/classes/_VDCNet-ejbPU.ejb] [
tid: _ThreadID=83 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1606311567437] [levelValue: 1000] [[
  
Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.6.payara-p1): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Access denied to execute this method : setURL
Error Code: 0
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:318)
        at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:150)
        at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:172)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:225)
        at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:809)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:256)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:772)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:222)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:330)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:350)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:313)
        at org.glassfish.persistence.jpa.JPADeployer$2.visitPUD(JPADeployer.java:461)
        at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:525)
        at org.glassfish.persistence.jpa.JPADeployer.iterateInitializedPUsAtApplicationPrepare(JPADeployer.java:507)
        at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:408)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:562)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:561)
```

and then a bunch of `Error in allocating a connection. Cause: Access denied to execute this method : setURL`

**Comment by poikilotherm** [comment]
This is related to payara/Payara#4864.

What version of Payara are you using by default? Upstream changed to 5.2020.6 with the merge of IQSS/dataverse#7419

**Comment by donsizemore** [comment]
still 5.2020.2; I can make Ansible default to 5.2020.6 if @pdurbin and others agree?

**Comment by qqmyers** [comment]
Sounds good to me. FWIW, I haven't seen issues running 5.1.1 or 5.2 with the latest payaras (.5 and .6)

**Comment by pdurbin** [comment]
Defaulting to the newer version of Payara sounds good to me. Thanks, @donsizemore .

**Comment by donsizemore** [comment]
integration tests return normally on Payara-5.2020.6:
    
<img width="456" alt="Screen Shot 2020-11-25 at 12 46 38" src="https://user-images.githubusercontent.com/12831666/100264694-2cf8ec00-2f1d-11eb-90be-9f9cb0c60869.png">
